"""initial schema

Hand-written rather than autogenerated: the partial indexes -- above all
`one_active_claim`, which is the entire concurrency guarantee (I2) -- cannot be
produced by autogenerate and must be exact.

Revision ID: 0001_initial
Revises:
Create Date: 2026-08-23
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001_initial"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


# --------------------------------------------------------------------------
# Native enum types
# --------------------------------------------------------------------------

ENUM_TYPES: dict[str, tuple[str, ...]] = {
    "user_role": ("customer", "organiser", "admin"),
    "booking_policy": ("open", "request"),
    "event_type": ("movie", "live"),
    "show_format": ("2D", "3D", "IMAX", "EPIQ_3D"),
    "show_status": ("scheduled", "cancelled", "completed"),
    "claim_state": ("held", "booked", "expired", "released"),
    "holder_type": ("user", "waitlist_offer"),
    "booking_status": ("confirmed", "cancelled"),
    "waitlist_entry_state": (
        "waiting",
        "offered",
        "converted",
        "declined",
        "cancelled",
    ),
    "waitlist_offer_state": ("pending", "claimed", "expired"),
    "outbox_state": ("pending", "sent", "failed"),
}


def enum(name: str) -> postgresql.ENUM:
    """Reference an already-created type; never emit CREATE TYPE."""
    return postgresql.ENUM(*ENUM_TYPES[name], name=name, create_type=False)


def pk() -> sa.Column:
    return sa.Column("id", sa.BigInteger(), sa.Identity(always=False), primary_key=True)


def created_at() -> sa.Column:
    return sa.Column(
        "created_at",
        sa.DateTime(timezone=True),
        nullable=False,
        server_default=sa.text("now()"),
    )


def upgrade() -> None:
    for name, values in ENUM_TYPES.items():
        rendered = ", ".join(f"'{value}'" for value in values)
        op.execute(f"CREATE TYPE {name} AS ENUM ({rendered})")

    # ---------------------------------------------------------------- identity
    op.create_table(
        "user_account",
        pk(),
        sa.Column("email", sa.String(255), nullable=False),
        sa.Column("password_hash", sa.String(255), nullable=False),
        sa.Column("name", sa.String(120), nullable=False),
        sa.Column("role", enum("user_role"), nullable=False),
        sa.Column("phone", sa.String(20), nullable=True),
        created_at(),
        sa.UniqueConstraint("email", name="uq_user_account_email"),
    )

    # ------------------------------------------------------------------ venues
    op.create_table(
        "venue",
        pk(),
        sa.Column("admin_id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.String(160), nullable=False),
        sa.Column("city", sa.String(80), nullable=False),
        sa.Column("address", sa.Text(), nullable=False),
        sa.Column("lat", sa.Numeric(9, 6), nullable=True),
        sa.Column("lng", sa.Numeric(9, 6), nullable=True),
        sa.Column(
            "booking_policy",
            enum("booking_policy"),
            nullable=False,
            server_default=sa.text("'open'"),
        ),
        created_at(),
        sa.ForeignKeyConstraint(
            ["admin_id"],
            ["user_account.id"],
            name="fk_venue_admin_id",
            ondelete="RESTRICT",
        ),
    )
    op.create_index("ix_venue_admin_id", "venue", ["admin_id"])
    op.create_index("ix_venue_city", "venue", ["city"])

    op.create_table(
        "screen",
        pk(),
        sa.Column("venue_id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.String(80), nullable=False),
        sa.Column(
            "total_seats", sa.Integer(), nullable=False, server_default=sa.text("0")
        ),
        created_at(),
        sa.ForeignKeyConstraint(
            ["venue_id"], ["venue.id"], name="fk_screen_venue_id", ondelete="CASCADE"
        ),
        sa.UniqueConstraint("venue_id", "name", name="uq_screen_venue_id_name"),
        sa.CheckConstraint("total_seats >= 0", name="total_seats_non_negative"),
    )

    op.create_table(
        "seat_category",
        pk(),
        sa.Column("screen_id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.String(60), nullable=False),
        sa.Column("rank", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["screen_id"],
            ["screen.id"],
            name="fk_seat_category_screen_id",
            ondelete="CASCADE",
        ),
        sa.UniqueConstraint("screen_id", "name", name="uq_seat_category_screen_id_name"),
        sa.CheckConstraint("rank > 0", name="rank_positive"),
    )

    op.create_table(
        "seat",
        pk(),
        sa.Column("screen_id", sa.BigInteger(), nullable=False),
        sa.Column("row_label", sa.String(4), nullable=False),
        sa.Column("seat_number", sa.Integer(), nullable=False),
        sa.Column("category_id", sa.BigInteger(), nullable=False),
        sa.Column("x", sa.Integer(), nullable=False),
        sa.Column("y", sa.Integer(), nullable=False),
        sa.Column(
            "is_active", sa.Boolean(), nullable=False, server_default=sa.text("true")
        ),
        sa.ForeignKeyConstraint(
            ["screen_id"], ["screen.id"], name="fk_seat_screen_id", ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["seat_category.id"],
            name="fk_seat_category_id",
            ondelete="RESTRICT",
        ),
        sa.UniqueConstraint(
            "screen_id",
            "row_label",
            "seat_number",
            name="uq_seat_screen_id_row_label_seat_number",
        ),
        sa.CheckConstraint("seat_number > 0", name="seat_number_positive"),
    )
    op.create_index("ix_seat_screen_id", "seat", ["screen_id"])
    op.create_index("ix_seat_category_id", "seat", ["category_id"])

    # ----------------------------------------------------------------- catalog
    op.create_table(
        "event",
        pk(),
        sa.Column("organiser_id", sa.BigInteger(), nullable=False),
        sa.Column("event_type", enum("event_type"), nullable=False),
        sa.Column("title", sa.String(200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("poster_url", sa.Text(), nullable=True),
        sa.Column("backdrop_url", sa.Text(), nullable=True),
        sa.Column("runtime_min", sa.Integer(), nullable=True),
        sa.Column("certification", sa.String(16), nullable=True),
        sa.Column(
            "genres",
            postgresql.ARRAY(sa.Text()),
            nullable=False,
            server_default=sa.text("'{}'::text[]"),
        ),
        sa.Column("release_date", sa.Date(), nullable=True),
        sa.Column("tmdb_id", sa.Integer(), nullable=True),
        sa.Column("artist_name", sa.String(160), nullable=True),
        created_at(),
        sa.ForeignKeyConstraint(
            ["organiser_id"],
            ["user_account.id"],
            name="fk_event_organiser_id",
            ondelete="RESTRICT",
        ),
        sa.CheckConstraint(
            "runtime_min IS NULL OR runtime_min > 0",
            name="runtime_positive",
        ),
    )
    op.create_index("ix_event_organiser_id", "event", ["organiser_id"])
    op.create_index("ix_event_event_type", "event", ["event_type"])

    op.create_table(
        "show",
        pk(),
        sa.Column("event_id", sa.BigInteger(), nullable=False),
        sa.Column("screen_id", sa.BigInteger(), nullable=False),
        sa.Column("organiser_id", sa.BigInteger(), nullable=False),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("language", sa.String(40), nullable=False),
        sa.Column("format", enum("show_format"), nullable=True),
        sa.Column(
            "status",
            enum("show_status"),
            nullable=False,
            server_default=sa.text("'scheduled'"),
        ),
        sa.Column(
            "seat_version", sa.Integer(), nullable=False, server_default=sa.text("0")
        ),
        created_at(),
        sa.ForeignKeyConstraint(
            ["event_id"], ["event.id"], name="fk_show_event_id", ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["screen_id"], ["screen.id"], name="fk_show_screen_id", ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["organiser_id"],
            ["user_account.id"],
            name="fk_show_organiser_id",
            ondelete="RESTRICT",
        ),
    )
    op.create_index("ix_show_event_id_starts_at", "show", ["event_id", "starts_at"])
    op.create_index("ix_show_screen_id_starts_at", "show", ["screen_id", "starts_at"])
    op.create_index("ix_show_organiser_id", "show", ["organiser_id"])

    op.create_table(
        "show_category_price",
        sa.Column("show_id", sa.BigInteger(), nullable=False),
        sa.Column("category_id", sa.BigInteger(), nullable=False),
        sa.Column("price", sa.Numeric(10, 2), nullable=False),
        sa.PrimaryKeyConstraint("show_id", "category_id", name="pk_show_category_price"),
        sa.ForeignKeyConstraint(
            ["show_id"],
            ["show.id"],
            name="fk_show_category_price_show_id",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["seat_category.id"],
            name="fk_show_category_price_category_id",
            ondelete="RESTRICT",
        ),
        sa.CheckConstraint("price >= 0", name="price_non_negative"),
    )

    # ----------------------------------------------------------------- booking
    op.create_table(
        "seat_claim",
        pk(),
        sa.Column("show_id", sa.BigInteger(), nullable=False),
        sa.Column("seat_id", sa.BigInteger(), nullable=False),
        sa.Column("hold_group_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("state", enum("claim_state"), nullable=False),
        sa.Column("holder_type", enum("holder_type"), nullable=False),
        sa.Column("holder_id", sa.BigInteger(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        created_at(),
        sa.ForeignKeyConstraint(
            ["show_id"], ["show.id"], name="fk_seat_claim_show_id", ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["seat_id"], ["seat.id"], name="fk_seat_claim_seat_id", ondelete="RESTRICT"
        ),
        sa.CheckConstraint(
            "state <> 'held' OR expires_at IS NOT NULL",
            name="held_claim_has_expiry",
        ),
        sa.CheckConstraint(
            "state <> 'booked' OR expires_at IS NULL",
            name="booked_claim_has_no_expiry",
        ),
    )
    op.create_index("ix_seat_claim_hold_group_id", "seat_claim", ["hold_group_id"])
    op.create_index("ix_seat_claim_seat_id", "seat_claim", ["seat_id"])

    op.create_table(
        "booking",
        pk(),
        sa.Column("reference", sa.String(10), nullable=False),
        sa.Column("show_id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("hold_group_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("total_amount", sa.Numeric(10, 2), nullable=False),
        sa.Column(
            "status",
            enum("booking_status"),
            nullable=False,
            server_default=sa.text("'confirmed'"),
        ),
        sa.Column("qr_signature", sa.String(64), nullable=True),
        sa.Column("checked_in_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        created_at(),
        sa.ForeignKeyConstraint(
            ["show_id"], ["show.id"], name="fk_booking_show_id", ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user_account.id"],
            name="fk_booking_user_id",
            ondelete="RESTRICT",
        ),
        sa.UniqueConstraint("reference", name="uq_booking_reference"),
        sa.CheckConstraint(
            "total_amount >= 0", name="total_amount_non_negative"
        ),
        sa.CheckConstraint(
            "reference ~ '^ESB-[A-Z0-9]{6}$'", name="reference_format"
        ),
    )
    op.create_index("ix_booking_user_id_created_at", "booking", ["user_id", "created_at"])
    op.create_index("ix_booking_show_id", "booking", ["show_id"])
    op.create_index("ix_booking_hold_group_id", "booking", ["hold_group_id"])

    op.create_table(
        "booking_seat",
        sa.Column("booking_id", sa.BigInteger(), nullable=False),
        sa.Column("seat_id", sa.BigInteger(), nullable=False),
        sa.Column("category_id", sa.BigInteger(), nullable=False),
        sa.Column("price", sa.Numeric(10, 2), nullable=False),
        sa.PrimaryKeyConstraint("booking_id", "seat_id", name="pk_booking_seat"),
        sa.ForeignKeyConstraint(
            ["booking_id"],
            ["booking.id"],
            name="fk_booking_seat_booking_id",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["seat_id"], ["seat.id"], name="fk_booking_seat_seat_id", ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["seat_category.id"],
            name="fk_booking_seat_category_id",
            ondelete="RESTRICT",
        ),
        sa.CheckConstraint("price >= 0", name="price_non_negative"),
    )

    # ---------------------------------------------------------------- waitlist
    op.create_table(
        "waitlist_entry",
        pk(),
        sa.Column("show_id", sa.BigInteger(), nullable=False),
        sa.Column("category_id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("qty", sa.Integer(), nullable=False),
        sa.Column(
            "state",
            enum("waitlist_entry_state"),
            nullable=False,
            server_default=sa.text("'waiting'"),
        ),
        created_at(),
        sa.ForeignKeyConstraint(
            ["show_id"], ["show.id"], name="fk_waitlist_entry_show_id", ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["seat_category.id"],
            name="fk_waitlist_entry_category_id",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user_account.id"],
            name="fk_waitlist_entry_user_id",
            ondelete="CASCADE",
        ),
        sa.CheckConstraint("qty > 0", name="qty_positive"),
    )
    op.create_index("ix_waitlist_entry_user_id", "waitlist_entry", ["user_id"])

    op.create_table(
        "waitlist_offer",
        pk(),
        sa.Column("entry_id", sa.BigInteger(), nullable=False),
        sa.Column("seat_ids", postgresql.ARRAY(sa.BigInteger()), nullable=False),
        sa.Column("token_hash", sa.String(64), nullable=False),
        sa.Column(
            "state",
            enum("waitlist_offer_state"),
            nullable=False,
            server_default=sa.text("'pending'"),
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        created_at(),
        sa.ForeignKeyConstraint(
            ["entry_id"],
            ["waitlist_entry.id"],
            name="fk_waitlist_offer_entry_id",
            ondelete="CASCADE",
        ),
        sa.UniqueConstraint("token_hash", name="uq_waitlist_offer_token_hash"),
        sa.CheckConstraint(
            "cardinality(seat_ids) > 0", name="seat_ids_not_empty"
        ),
    )
    op.create_index("ix_waitlist_offer_entry_id", "waitlist_offer", ["entry_id"])

    # ------------------------------------------------------------ infrastructure
    op.create_table(
        "outbox",
        pk(),
        sa.Column("template", sa.String(64), nullable=False),
        sa.Column("to_email", sa.String(255), nullable=False),
        sa.Column(
            "payload",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default=sa.text("'{}'::jsonb"),
        ),
        sa.Column(
            "state",
            enum("outbox_state"),
            nullable=False,
            server_default=sa.text("'pending'"),
        ),
        sa.Column("attempts", sa.Integer(), nullable=False, server_default=sa.text("0")),
        sa.Column("last_error", sa.Text(), nullable=True),
        created_at(),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("attempts >= 0", name="attempts_non_negative"),
    )

    op.create_table(
        "idempotency_key",
        sa.Column("key", sa.String(80), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("endpoint", sa.String(120), nullable=False),
        sa.Column("response_body", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("status_code", sa.Integer(), nullable=False),
        created_at(),
        sa.PrimaryKeyConstraint("key", "user_id", name="pk_idempotency_key"),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user_account.id"],
            name="fk_idempotency_key_user_id",
            ondelete="CASCADE",
        ),
    )

    # ------------------------------------------------------------------------
    # Partial indexes.
    #
    # `one_active_claim` IS the concurrency control (I2). Two transactions that
    # try to claim the same seat for the same show at the same instant both
    # reach the INSERT; PostgreSQL serialises them on this index and exactly
    # one survives. There is no application-level lock, and no check-then-act.
    # Expired and released claims fall out of the predicate, so a seat can be
    # re-claimed without ever deleting history.
    # ------------------------------------------------------------------------
    op.execute(
        """
        CREATE UNIQUE INDEX one_active_claim ON seat_claim (show_id, seat_id)
            WHERE state IN ('held','booked')
        """
    )
    # Seat-map read path: every live claim for one show.
    op.execute(
        """
        CREATE INDEX ix_seat_claim_show_active ON seat_claim (show_id)
            WHERE state IN ('held','booked')
        """
    )
    # Sweeper scan: the oldest holds due to expire.
    op.execute(
        """
        CREATE INDEX ix_seat_claim_expiry_sweep ON seat_claim (expires_at)
            WHERE state = 'held'
        """
    )
    # Waitlist queue order, oldest first, per (show, category).
    op.execute(
        """
        CREATE INDEX ix_waitlist_entry_queue
            ON waitlist_entry (show_id, category_id, created_at)
            WHERE state = 'waiting'
        """
    )
    # One live waitlist entry per user per show per category.
    op.execute(
        """
        CREATE UNIQUE INDEX uq_waitlist_entry_active_per_user
            ON waitlist_entry (show_id, category_id, user_id)
            WHERE state IN ('waiting','offered')
        """
    )
    # Sweeper scan for lapsed offers.
    op.execute(
        """
        CREATE INDEX ix_waitlist_offer_pending_expiry ON waitlist_offer (expires_at)
            WHERE state = 'pending'
        """
    )
    # Outbox dispatcher: oldest undelivered mail first.
    op.execute(
        """
        CREATE INDEX ix_outbox_pending ON outbox (created_at)
            WHERE state = 'pending'
        """
    )


def downgrade() -> None:
    for table in (
        "idempotency_key",
        "outbox",
        "waitlist_offer",
        "waitlist_entry",
        "booking_seat",
        "booking",
        "seat_claim",
        "show_category_price",
        "show",
        "event",
        "seat",
        "seat_category",
        "screen",
        "venue",
        "user_account",
    ):
        op.drop_table(table)

    for name in ENUM_TYPES:
        op.execute(f"DROP TYPE IF EXISTS {name}")
